name: flutter_color_pickr
description: A simple color picker for flutter.
version: 1.0.0
repository: https://github.com/mj12358/flutter-color-picker

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
