name: flutter_color_pickr
description: A simple color picker for flutter utilizing material designs primary colors.
version: 1.0.1
repository: https://github.com/mj12358/flutter-color-picker

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_lintz: ^1.0.0
  flutter_test:
    sdk: flutter
